version: "3.8"
services:
  app:
    container_name: geocode-flask
    build: .
    # image: geocode-flask
    command: python setup.py
    environment: 
        - FLASK_APP=setup.py
        - FLASK_ENV=production
    ports:
      - "5000:5000"
    volumes:
      - .:/geocode-flask